#define MAXPATH 128
#define MAXCMD (MAXPATH + MAXPATH + 10)
#define MAXARGS 10


#define MAGICNUM 0xdec0de
#define DATABLKSZ 1024
#define INODESZ 32
#define DIRITEMSZ 128
#define SUPERBLKLOC 0

#define NINODE_PER_BLK 32
#define NDIRITEM_PER_BLK 8

#define INVALID_INODE_POINT ((uint32)0)
